### ISSUE TITLE
PBCC issue

### ISSUE THREAD

**Issue by s21sm** [5GSEC/MobieXpert#1]
Hi, Thank you very much for the interesting application. I am having some difficulties while building MobieXpert. It is related to pbcc, I think my machine does not have it.

```
 => CACHED [ 2/10] WORKDIR /usr/local                                                                                                                                     0.0s
 => CACHED [ 3/10] RUN pip install grpcio grpcio-tools                                                                                                                    0.0s
 => CACHED [ 4/10] RUN apt-get update && apt-get -y install build-essential gcc-multilib flex csh                                                                         0.0s
 => CACHED [ 5/10] COPY mobi-expert-xapp/setup.py ./mobi-expert-xapp/setup.py                                                                                             0.0s
 => CACHED [ 6/10] RUN pip install ./mobi-expert-xapp --no-cache-dir                                                                                                      0.0s
 => CACHED [ 7/10] COPY mobi-expert-xapp ./mobi-expert-xapp                                                                                                               0.0s
 => CACHED [ 8/10] RUN pip install ./mobi-expert-xapp --no-cache-dir                                                                                                      0.0s
 => ERROR [ 9/10] RUN cd mobi-expert-xapp/pbest/expert && make clean && make                                                                                              0.4s
------                                                                                                                                                                         
 > [ 9/10] RUN cd mobi-expert-xapp/pbest/expert && make clean && make:
0.349 rm -f *.o rules.c main
0.369 ../pbcc/Linux-x86_64/Debian-5.15/pbcc -j -v -e -o rules.c rules.pbest
0.369 make: ../pbcc/Linux-x86_64/Debian-5.15/pbcc: No such file or directory
0.369 make: *** [Makefile:61: rules.c] Error 127
```
Could you please give some hints about pbcc (I already read the linked paper but did not find how to solve the issue) and from where I get it.

Thanks

**Comment by onehouwong** [comment]
Hi, Thank you for your feedback. It looks like you are working with our VM artifact.

We have released the MobieXpert source code now (https://github.com/5GSEC/MobieXpert), which has included the pbcc executable for Linux 64. However, we could not release the pbcc source code due to some proprietary issues.

Could you follow this new guide (https://github.com/5GSEC/5G-Spector/wiki/Build-5G%E2%80%90Spector-from-scratch-in-an-OAI-5G-network) to clone both MobiFlow Auditor and MobieXpert to built them?

**Comment by onehouwong** [comment]
Hi, Thank you for your feedback. Looks like this is related to the path naming problem since you are using Debian 5.15. Could you try renaming the folder under `../pbcc/Linux-x86_64/Debian-5.14/`  to `../pbcc/Linux-x86_64/Debian-5.15/`?

We have pushed a new fix to make it agnostic to kernel versions. Feel free to try that as well!
